In [1]:
#writing the data to the text file
with open("nit.text","w")as fp:
    fp.write("1.0 2.0 3.0\n 4.0 5.0 6.0\n7.0 8.0 9.0")
    print("text file created and data saved in file:")

text file created and data saved in file:


In [5]:
#read the Data from text File
try:
    with open('nit.text',"r") as fp:
        filedata=fp.read()
        print("File Data")
        print(filedata)
except FileNotFoundError:
    print("File Does not Exist")

File Data
1.0 2.0 3.0
 4.0 5.0 6.0
7.0 8.0 9.0


In [9]:
#read the data from text file by using numpy.loadtxt()
import numpy as np
filedata=np.loadtxt("nit.text")
print("file data")
print(filedata,type(filedata))

file data
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] <class 'numpy.ndarray'>


In [13]:
#program for demonstrating writing the ndarray object data to the text file 
a=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
print("given ndarray object")
print(a)
print("*"*50)
np.savetxt("nit1.text",a)
print("nd array data saved in text file")

given ndarray object
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
**************************************************
nd array data saved in text file


In [ ]:
#program for demostrating writing the ndarray object data to birany file

In [40]:
import numpy as np
a=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
print("given ndaarray object")
print(a)
np.save("nit5.npy",a)
print("ndarray data saved in binary file---verify")

given ndaarray object
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
ndarray data saved in binary file---verify


In [44]:
filedata=np.load("nit5.npy")
print("file data")
print(filedata)

file data
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [46]:
#Program for Demonstrating Reading data from Binary file into ndarray object
filedata=np.load("nit5.npy")
print("File Data")
print(filedata[0:1,::],type(filedata))

File Data
[[1. 2. 3.]] <class 'numpy.ndarray'>


In [54]:
#writing the data to the csv file
import numpy as np
with open('nit6.csv','w')as fp:
    fp.write("1.0 2.0 3.0/n 4.0 5.0 6.0\n7.0 8.0 9.0")
    print("csv file created and data saved in file:")

csv file created and data saved in file:


In [64]:
#reading the data from the saved in file:
import numpy as np
filedata2=np.genfromtxt('nit6.csv',delimiter=',')
print(filedata,type(filedata2))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] <class 'numpy.ndarray'>


In [78]:
#Reading  the Data from the CSV File where It contains str data
import numpy as np
filedata=np.genfromtxt('C:\\Users\\prash\\OneDrive\\Desktop\\Numpy\\Numpy CLASS NOTES ON 11-02-2025\\anil.csv',delimiter=',')
print(filedata,type(filedata))

[nan nan nan nan] <class 'numpy.ndarray'>


In [76]:
#Reading  the Data from the CSV File where It contains str data
import numpy as np
filedata=np.genfromtxt('C:\\Users\\prash\\OneDrive\\Desktop\\Numpy\\Numpy CLASS NOTES ON 11-02-2025\\anil.csv',delimiter=',',dtype="str")
print(filedata,type(filedata))

['[["prasahant"' '"anil"]' '["sai"' '"raju"]]'] <class 'numpy.ndarray'>


In [82]:
#Reading  the Data from the CSV File where It contains str data
import numpy as np
filedata=np.loadtxt('C:\\Users\\prash\\OneDrive\\Desktop\\Numpy\\Numpy CLASS NOTES ON 11-02-2025\\anil.csv',delimiter=',',dtype="str")
print(filedata,type(filedata))

['[["prasahant"' '"anil"]' '["sai"' '"raju"]]'] <class 'numpy.ndarray'>


In [94]:
#create a numpyarray with both numeric  and string data
import numpy as np
a=np.array([[1,'gudio',95.5],[2,'travis',90.0]],dtype=object)
print("content of the ndarray")
print(a,type(a))

content of the ndarray
[[1 'gudio' 95.5]
 [2 'travis' 90.0]] <class 'numpy.ndarray'>


In [98]:
#Write the above ndarray data to CSV File
import csv
with open("ndnit.csv","w") as fp:
    csvwr=csv.writer(fp)
    csvwr.writerows(a) # Here 'a' is called ndarray object
    print("ND Array data written to the  file--verify")

ND Array data written to the  file--verify


In [100]:
import numpy as np
import csv
# Create a NumPy array with both numeric and string data
a = np.array([
    [1, 'GUIDO ROSSUM', 95.5],
    [2, 'TRAVIS OLIPHANT', 90.0],
    [3, 'DENNIS RITCHE', 80.0],
    [4, 'JHON HUNTER', 91.5]
], dtype=object)
with open("ndnit2.csv","w") as fp:
    csvwr=csv.writer(fp)
    for row in a:
        csvwr.writerow(row)
print("ND Array data written to the  file--verify")

ND Array data written to the  file--verify


In [102]:
#Most IMP: This Reads the Data from CSV File where It Contains Different Col names with Diff type
import numpy as np
# Define the path to the CSV file
csv_file_path = "sci.csv"
# Define the data types for each column
dtype = [('ID', 'i4'), ('Name', 'U10'), ('Score', 'f4')]

# Read the CSV file into a structured NumPy array
sa = np.genfromtxt(csv_file_path, delimiter=',', dtype=dtype, names=True)

# Print the structured NumPy array
print(sa,type(sa))

FileNotFoundError: sci.csv not found.

In [104]:
#Most Imp: Writing the Ndarray object data to text File and Reading the Text File Data
import numpy as np
# Create a NumPy array
data_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Define the path to the text file
text_file_path = "data.txt"

# Save the NumPy array to a text file with space as the delimiter
np.savetxt(text_file_path, data_array)
print("------------------------------------------------------")
print("ndarray object Data saved in text File")
print("------------------------------------------------------")
# Read the text file back into a NumPy array
loaded_array = np.loadtxt(text_file_path)
# Print the original and loaded NumPy arrays
print("Original NumPy Array:")
print(data_array)

------------------------------------------------------
ndarray object Data saved in text File
------------------------------------------------------
Original NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
print("Original NumPy Array:")
print(data_array)
print(data_array.dtype)

Original NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


In [108]:
print("Original NumPy Array with float:")
loaded_array=loaded_array.astype(float)
print(loaded_array.dtype)

Original NumPy Array with float:
float64


In [110]:
print("Original NumPy Array with float:")
loaded_array=loaded_array.astype("i2")
print(loaded_array)
print(loaded_array.dtype)

Original NumPy Array with float:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int16


In [122]:
#save the Dict Object into Json File
import json
import numpy as np
dictobj={'id': '09', 'name': 'Rossum', 'department': 'IT'} 
with open("nit10.json","w") as fp:
    json.dump(dictobj,fp)
    print("Dict data saved in Json File--verify")

Dict data saved in Json File--verify


In [124]:
with open("nit10.json","r") as fp:
    js=json.load(fp)
    a=np.array(js)
    print(a)
    print("Dict data saved in Json File--verify")

{'id': '09', 'name': 'Rossum', 'department': 'IT'}
Dict data saved in Json File--verify


In [126]:
for key,val in js.items(): # here jsondata is of type <class,dict>
    print("\t{}-->{}".format(key,val))

	id-->09
	name-->Rossum
	department-->IT
