In [1]:
#deleting--->delete(index,val),inseting--->insert(indesx,val),appending-->append(val)
#note here axis=0---row,axis=1---col


In [9]:
import numpy as np
a=np.array([10,20,30,40,40,50,])
print("content of a")
print(a)
print("dimesion--->",a.ndim)

content of a
[10 20 30 40 40 50]
dimesion---> 1


In [21]:
#append the value in the 1d--array
print("before appending the val")
print(a)
a=np.append(a,10)
print("after appending the val")
print(a)

before appending the val
[10 20 30 40 40 50 10]
after appending the val
[10 20 30 40 40 50 10 10]


In [13]:
a=np.append(a,[10,20,30,40,])
print("after appending the val")
print(a)

after appending the val
[10 20 30 40 10 30 10 20 30 40]


In [11]:
#addin the the value in the row
import numpy as np
a=np.array([[10,20],[30,40]])
a=np.append(a,[[10,30]],axis=0)
print(a)

[[10 20]
 [30 40]
 [10 30]]


In [27]:
a=np.array([40,50,60,30,70,80,40,50,40]).reshape(3,3)
print(a)
a=np.append(a,[[10,20,30]],axis=0)
print("after updating the value")
print(a)

[[40 50 60]
 [30 70 80]
 [40 50 40]]
after updating the value
[[40 50 60]
 [30 70 80]
 [40 50 40]
 [10 20 30]]


In [35]:
#now insertingbthe value into the col
import numpy as np
a=np.array([40,50,60,30,40,50]).reshape(2,3)
print(a)
a=np.append(a,[[60],[40]])
print("after updating the values")
print(a)

[[40 50 60]
 [30 40 50]]
after updating the values
[40 50 60 30 40 50 60 40]


In [37]:
#inserting the values into the 1-d,2d
#insert(ind,val)
import numpy as np
a=np.array([10,20,30,40,50,60,70])
print(a)

[10 20 30 40 50 60 70]


In [51]:
#now we are inserting the value into the 1d array
#insert of insert(a,ind,value)
a=np.insert(a,0,20)
print(a)

[20 10 20 30 40 50 60 70]


In [53]:
import numpy as np
a=np.array([10,20,30,40,50,60,70])
print(a)
a=np.insert(a,-1,20)
print(a)

[10 20 30 40 50 60 70]
[10 20 30 40 50 60 20 70]


In [57]:
#2d--array inserting the data 
a=np.array([10,20,30,40]).reshape(2,2)
print(a)
#insertingbthe the value
a=np.insert(a,1,[[50,60]],axis=0)
print(a)

[[10 20]
 [30 40]]
[[10 20]
 [50 60]
 [30 40]]


In [61]:
#2d--array inserting the data 
a=np.array([10,20,30,40]).reshape(2,2)
print(a)
#insertingbthe the value
a=np.insert(a,1,[[50,60]],axis=1)
print(a)

[[10 20]
 [30 40]]
[[10 50 20]
 [30 60 40]]


In [1]:
#here we are doing the delete operation
#delte(index,value,axis)

In [11]:
import numpy as np
a=np.array([10,20,30,40,50,40,56])
print("content of a ")
print("before deleting the value ")
print(a)
#here we are using the delete operation
print("after deleting the value ")
a=np.delete(a,-1)
print(a)

content of a 
before deleting the value 
[10 20 30 40 50 40 56]
after deleting the value 
[10 20 30 40 50 40]


In [13]:
#deleting the three values
a=np.array([10,20,40,55,66,78])
print("content of a ")
print("before deleting the value ")
print(a)
a=np.delete(a,[0,1,-1])
print("after deleting the value")
print(a)


content of a 
before deleting the value 
[10 20 40 55 66 78]
after deleting the value
[40 55 66]


In [67]:
#we are  deleting the rows from the 2d matrix
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print(a)
#deleting the values from the matrix
a=np.delete(a,0,axis=0)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[40 50 60]
 [70 80 90]]


In [69]:
a=np.delete(a,1,axis=1)
print(a)

[[40 60]
 [70 90]]


In [76]:
a[0:1,:]=[50,60]
print(a)

[[50 60]
 [70 90]]


[[50 60]
 [50 60]]
