In [ ]:
# The copy returns None.
# The view returns the original array.

In [29]:
#copy(),veiw()
#here copyis ashallow copy it had diffrent id and no base
#where view has the diferent id and and base 
import numpy as np 
a=np.array([10,20,30,40,50,60,70,80])
print(a,id(a))
print("content of a")
print("dim of a =",a.ndim)
print("shape of a=",a.shape)
print("-"*52)
#copy()
b=np.copy(a)
print(b,id(b),b.base)

[10 20 30 40 50 60 70 80] 1755416111664
content of a
dim of a = 1
shape of a= (8,)
----------------------------------------------------
[10 20 30 40 50 60 70 80] 1755416111184 None


In [31]:
c=b.copy()
print(c,id(c))
a[0]=20
print(a,b)

[100  20  30  40  50  60 -12] 2241293581072
[ 20  20  30  40  50  60 -12] [ 20  20  30  40  50  60 -12]


In [41]:
a=np.append(a,100)
b=np.append(b,200)
#here we append t
print(a,b,id(a))

[ 10  20  30  40  50  60  70  80 100 100 100 100] [ 10  20  30  40  50  60  70  80 200 200 200 200] 1755416113488


In [5]:
import numpy as np
a=np.array([10,20,30,40,50,60,80,])
print(a,id(a))
#here the id is diferet od pervious and copy
b=a.view()
print(b,id(b))

[10 20 30 40 50 60 80] 2241252441136
[10 20 30 40 50 60 80] 2241252441232


In [17]:
c=b.copy()
print(c,id(c))

[100  20  30  40  50  60  80] 2241252441040


In [25]:
a[0]=100
print(a,b)
a[-1]=-12
print(c)
print("original obj{},view obj{},copyobj{}".format(a,b,c))

[100  20  30  40  50  60  80] [100  20  30  40  50  60  80]
[100  20  30  40  50  60  80]
original obj[100  20  30  40  50  60 -12],view obj[100  20  30  40  50  60 -12],copyobj[100  20  30  40  50  60  80]


In [29]:
print("original obj{},view obj{}---base{},copyobj{}-----base{}".format(a,b,c,b.base,c.base))

original obj[100  20  30  40  50  60 -12],view obj[100  20  30  40  50  60 -12]---base[100  20  30  40  50  60  80],copyobj[100  20  30  40  50  60 -12]-----baseNone
