In [9]:
#here we are going to study of faltten(),ravel()
# here flaten is used for convrert nd arrat to 1d array
import numpy as np
a=np.array([10,30,30,40,50,60]).reshape(2,3)
print(a)
#flatten()
b=a.flatten()
print(b)

[[10 30 30]
 [40 50 60]]
[10 30 30 40 50 60]


In [21]:
print("shape=",a.shape)
print("size=",a.size)
print("dim=",a.ndim)
#copy ied value here is
print("-"*50)
print("shape=",b.shape)
print("size=",b.size)
print("dim=",b.ndim)

shape= (2, 3)
size= 6
dim= 2
--------------------------------------------------
shape= (6,)
size= 6
dim= 1


In [69]:
#here are using the reval()
a=np.random.randint(10,20,size=(2,2,3))
print(a)
#here we are converting the 1-d array
b=a.flatten()
print(b)
c=b.ravel()
print(c)

[[[13 12 10]
  [18 14 16]]

 [[17 12 16]
  [12 18 14]]]
[13 12 10 18 14 16 17 12 16 12 18 14]
[13 12 10 18 14 16 17 12 16 12 18 14]


In [67]:
print("{} original value".format(a))
print("{} view value base---->{}".format(b,b.base))
print("{} copied value base--->{}".format(c,c.base))

[[[100 100 100]
  [100 100 100]]

 [[ 12  11  16]
  [ 16  18  14]]] original value
[100  13  19  14  13  16  12  11  16  16  18  14] view value base---->None
[100  13  19  14  13  16  12  11  16  16  18  14] copied value base--->[100  13  19  14  13  16  12  11  16  16  18  14]


In [73]:
a[0,0,0]=11
print(a)
print("-----")
print(b)
print("------")
print(c)


[[[11 12 10]
  [18 14 16]]

 [[17 12 16]
  [12 18 14]]]
-----
[13 12 10 18 14 16 17 12 16 12 18 14]
------
[13 12 10 18 14 16 17 12 16 12 18 14]


In [75]:
c[1]=10
print(a)
print("-----")
print(b)
print("------")
print(c)

[[[11 12 10]
  [18 14 16]]

 [[17 12 16]
  [12 18 14]]]
-----
[13 10 10 18 14 16 17 12 16 12 18 14]
------
[13 10 10 18 14 16 17 12 16 12 18 14]
