In [1]:
#dot (),inner(),outer(),det(),solve(),inv(),trance()


In [7]:
import numpy as np
a=np.array([[10,20],[20,30]])
print("content of a")
print(a)

content of a
[[10 20]
 [20 30]]


In [11]:
#now we are per forming the dot prodect to it
a1=np.array([10,20,40,20,30,40,50])
a2=np.array([10,20,30,40,50,60,70])
print("dot")
b=np.dot(a1,a2)
print(b)

dot
9900


In [13]:
#now we are performin the inner operation 
a1=np.array([10,20,30,40])
a2=np.array([10,20,30,40])
print("inner operation")
print("-"*50)
b=np.inner(a1,a2)
print(b)

inner operation
--------------------------------------------------
3000


In [37]:
#now we are per forming the inner operation to 2d array
a=np.array([10,21,23,44,45,96]).reshape(2,3)
print("matrix-a")
print(a)
b=np.array([10,21,23,44,45,96]).reshape(2,3)
print("matrix-b")
print(b)
print("inner operation")
c=np.inner(a,b)
print(c)

matrix-a
[[10 21 23]
 [44 45 96]]
matrix-b
[[10 21 23]
 [44 45 96]]
inner operation
[[ 1070  3593]
 [ 3593 13177]]


In [23]:
#now we are per for min the outer operation to 1d array
a=np.array([10,20,30,40,50])
b=np.array([10,20,30,40,50])
print("outer operation")
c=np.outer(a,b)
print(c)

outer operation
[[ 100  200  300  400  500]
 [ 200  400  600  800 1000]
 [ 300  600  900 1200 1500]
 [ 400  800 1200 1600 2000]
 [ 500 1000 1500 2000 2500]]


In [ ]:
#now we are performin the det operation the 2d array

In [39]:
import numpy as np
a=np.array([40,50,60,70]).reshape(2,2)
print(a)
print("per formin the det operation ot it")
b=np.linalg.det(a)
print(b)

[[40 50]
 [60 70]]
per formin the det operation ot it
-200.0000000000001


In [47]:
import numpy as np
a=np.array([40,50,60,70,80,90,50,60,90]).reshape(3,3)
print(a)
print("per formin the det operation ot it")
b=np.linalg.det(a)
print("thr det of 2d matrix is--->",b)

[[40 50 60]
 [70 80 90]
 [50 60 90]]
per formin the det operation ot it
thr det of 2d matrix is---> -6000.000000000006


In [57]:
#now we are per formin the solveoperation to the 2d array
import numpy as np 
a1=np.array([40,50,60,80]).reshape(2,2)
a2=np.array([40,50,60,80]).reshape(2,2)
print("1-st matrix")
print(a1)
print("2-nd matrix")
print(a2)
print("performing the solve operation")
b=np.linalg.solve(a1,a2)
print(b)

1-st matrix
[[40 50]
 [60 80]]
2-nd matrix
[[40 50]
 [60 80]]
performing the solve operation
[[ 1.00000000e+00  0.00000000e+00]
 [-6.66133815e-16  1.00000000e+00]]


In [59]:
#now we are per formin the solveoperation to the 2d array
import numpy as np 
a1=np.array([40,50,60,80,50,60,60,80,77]).reshape(3,3)
a2=np.array([40,50,60,80,50,60,60,80,77]).reshape(3,3)
print("1-st matrix")
print(a1)
print("2-nd matrix")
print(a2)
print("performing the solve operation")
b=np.linalg.solve(a1,a2)
print(b)

1-st matrix
[[40 50 60]
 [80 50 60]
 [60 80 77]]
2-nd matrix
[[40 50 60]
 [80 50 60]
 [60 80 77]]
performing the solve operation
[[ 1.00000000e+00  8.88178420e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.45018082e-17  1.00000000e+00]]


In [75]:
#now we are per forming the inv() of 2d array
import numpy as np
a=np.array([10,20,30,40,50,60,11,11,11]).reshape(3,2)
print(a)
print("inveres of the matrix")
b=np.linalg.inv(a)
print(a)

[[10 20]
 [30 40]]
inveres of the matrix
[[-0.2   0.1 ]
 [ 0.15 -0.05]]
