In [1]:
#numpy of nd array of arthematic opereator
#there are 7 types
# add(),subtract(),multiply(),divide(),dot() or matmul(),floor_dived (),mod(),power()

In [31]:
import numpy as np
a=np.array([[1,2],[10,12]])
print("content of a")
print(a)
print("shape of ",a.shape)

content of a
[[ 1  2]
 [10 12]]
shape of  (2, 2)


In [33]:
b=np.array([10,20,30,40]).reshape(2,2)
print(b)

[[10 20]
 [30 40]]


In [35]:
#here add() is adding 
c=np.add(a,b)
print(c)

[[11 22]
 [40 52]]


In [37]:
d=np.sbutract(a,b)
print(d)

AttributeError: module 'numpy' has no attribute 'sbutract'