In [1]:
# numpy aproch the rundig the decimals around(),fix(),trunc(),floor(),ceil()


In [5]:
import numpy as np
a=np.array([10,20,30,40,50,70]).reshape(2,3)
print("content of the a")
print(a)
print(a.shape)
print("dim of the a",a.ndim)

content of the a
[[10 20 30]
 [40 50 70]]
(2, 3)
dim of the a 2


In [15]:
a1=np.array([10,20,30,40])
a2=np.array([30,50,60,80])
c=np.divide(a1,a2)
print(c)

[0.33333333 0.4        0.5        0.5       ]


In [17]:
#--->it will elminates the decimal values
d=np.around(c)
print(d)

[0. 0. 0. 0.]


In [23]:
d=np.fix(c)
print(d)

[0. 0. 0. 0.]


In [25]:
import numpy as np 
a=np.trunc([10.666,0.336,17.55])
print(a)

[10.  0. 17.]


In [27]:
import numpy as np 
a=np.trunc([10.666,0.336,17.55,3.665,17.1666])
print(a)

[10.  0. 17.  3. 17.]


In [29]:
import numpy as np 
a=np.fix([10.666,0.336,17.55,3.665,17.1666])
print(a)

[10.  0. 17.  3. 17.]


In [31]:
import numpy as np 
a=np.fix([1.666,0.336,16.55,3.665,17.1666])
print(a)

[ 1.  0. 16.  3. 17.]


In [33]:
#now  we are usig the around operation
a=np.around([20.14,55.166,23.114])
print(a)

[20. 55. 23.]


In [35]:
#now  we are usig the floor operation
a=np.floor([20.14,55.166,23.114])
print(a)

[20. 55. 23.]


In [41]:
#now we are performing the ceil()
a=np.ceil([20.156,55.1666,23.114])
print(a)

[21. 56. 24.]
