In [1]:
#the set operation the numpy we are performing the the number of aporcahes of the set operation

In [3]:
#unique(),union1d(),intersectd1(),setdiff1d(),setxor1d()--->this thye perdine function of the set in the numpy

In [5]:
import numpy as np
a=np.array([10,20,30])
a2=np.array([20,30,40])
print(a,a2)
#now we unique 

[10 20 30] [20 30 40]


In [11]:
c=np.unique([a,a2])
print(c)

[10 20 30 40]


In [13]:
a=np.array([10,20,30,20,40,30])
c=np.unique(a)
print(c)

[10 20 30 40]


In [21]:
#now are performin the union operartion--> it will elminate the a number which is repeated more than on time
a1=np.array([10,20,30])
a2=np.array([20,40,50])
print(a1,a2)
c=np.union1d(a1,a2)
print("permoing the union")
print(c)

[10 20 30] [20 40 50]
permoing the union
[10 20 30 40 50]


In [23]:
#now are performin the setdiff1d operartion--> it will elminate the common element of a1,a2 --->it will print first set of elements
a1=np.array([10,20,30])
a2=np.array([20,40,50])
print(a1,a2)
c=np.setdiff1d(a1,a2)
print(c)

[10 20 30] [20 40 50]
[10 30]


In [25]:
#now are performin the setdiff1d operartion--> it will print only common elements
a1=np.array([10,20,30])
a2=np.array([20,40,50])
print(a1,a2)
c=np.intersect1d(a1,a2)
print(c)

[10 20 30] [20 40 50]
[20]


In [27]:
#now are performin the setdiff1d operartion--> it will print only the uniue elements 
a1=np.array([10,20,30])
a2=np.array([20,40,50])
print(a1,a2)
c=np.setxor1d(a1,a2)
print(c)

[10 20 30] [20 40 50]
[10 30 40 50]
