In [15]:
#here simple arthematic in nmupyis simmilar to the the python arthematic operation 
# add(),subtract(),multiply(),divide(),mod(),power(),dividemode(),absolute()
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("addition operation")
c=np.add(a,b)
print(c)

addition operation
[ 30  74 100 176]


In [19]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("subratcting operation")
c=np.subtract(a,b)
print(c)

subratcting operation
[-10  14  10  16]


In [23]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("multiple operation")
c=np.multiply(a,b)
print(c)

multiple operation
[ 200 1320 2475 7680]


In [11]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("multiple operation")
c=np.dot(a,b)
print(c)

multiple operation
11675


In [31]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("dived operation")
c=np.divide(a,b)
print(c)

dived operation
[0.5        1.46666667 1.22222222 1.2       ]


In [33]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("mode operation")
c=np.mod(a,b)
print(c)

dived operation
[10 14 10 16]


In [35]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("power operation")
c=np.power(a,b)
print(c)

power operation
[1661992960          0  571719255          0]


In [39]:
import numpy as np 
a=np.array([10,44,55,96])
b=np.array([20,30,45,80])
print("dividemod operation")#---> it gives the floor div and mod
c=np.divmod(a,b)
print(c)

dividemod operation
(array([0, 1, 1, 1]), array([10, 14, 10, 16]))


In [43]:
import numpy as np
a=np.array([10,-2,-4,-16,-23])
print("comtent of a")
print("perfroming the abolute value")
b=np.absolute(a)#----> it convert the the neg to posti
print(b)

comtent of a
perfroming the abolute value
[10  2  4 16 23]
