In [3]:
#sort() here we are sorting the the nd array
#here axis=0 col,axis=1 row
import numpy as np
a=np.array([20,20,70,90,56,78])
print(a)
print("sorting the 1-d array")
a=np.sort(a)
print(a)

[20 20 70 90 56 78]
sorting the 1-d array
[20 20 56 70 78 90]


In [5]:
# now weare sorting into reverse order 
print("sorting to revserse order")
a=np.sort(a)[::-1]
print(a)

sorting to revserse order
[90 78 70 56 20 20]


In [11]:
#now we are finding the largest muber of 1-d array
print(a)
print("max value of the array")
b=a[0]
print("maxvalue=",b)
print("min value of the array")
a=np.sort(a)
b=a[0]
print("minvalue=",b)

[90 78 70 56 20 20]
max value of the array
maxvalue= 90
min value of the array
minvalue= 20


In [17]:
#now we are sorting the the 2d matrix col
import numpy as np
a=np.array([10,55,88,12,13,45]).reshape(2,3)
print("matrix before sorting")
print(a)
print("matrix after sorting")
a=np.sort(a,axis=0)
print(a)

matrix before sorting
[[10 55 88]
 [12 13 45]]
matrix after sorting
[[10 13 45]
 [12 55 88]]


In [19]:
#now we are sorting the the 2d matrix row 
import numpy as np
a=np.array([10,55,88,12,13,45]).reshape(2,3)
print("matrix before sorting")
print(a)
print("matrix after sorting")
a=np.sort(a,axis=1)
print(a)

matrix before sorting
[[10 55 88]
 [12 13 45]]
matrix after sorting
[[10 55 88]
 [12 13 45]]
