In [1]:
#staticial opartion in numpy there are 
#amax(),amin(),mean()

In [3]:
import numpy as np
a=np.random.randint(10,30,size=15)
print("content of a")
print(a)

content of a
[11 17 22 27 10 25 28 26 27 13 10 22 25 12 18]


In [5]:
#find the max,min
maxv=np.amax(a)
minv=np.amin(a)
print("max value=",maxv)
print("min value=",minv)

max value= 28
min value= 10


In [21]:
a=np.array([10,20,30,40,60,70,80,50]).reshape(2,4)
print(a)
print("dim of a=",a.ndim)
print("maximum of a=",np.max(a))
print("minimum of a=",np.min(a))

[[10 20 30 40]
 [60 70 80 50]]
dim of a= 2
maximum of a= 80
minimum of a= 10


In [23]:
#Find Max and min Values from ndarray--2 Dim
a=np.random.randint(10,30,size=(4,4))
print("--------------------------------------")
print("Content of a")
print(a)
print("--------------------------------------")
maxv=np.amax(a)
minv=np.amin(a)
print("Max Value=",maxv)
print("Min Value=",minv)
print("--------------------------------------")

--------------------------------------
Content of a
[[16 23 22 22]
 [22 26 15 12]
 [26 29 19 11]
 [29 23 11 11]]
--------------------------------------
Max Value= 29
Min Value= 11
--------------------------------------


In [27]:
#now req is colwise and row wise 
#here if axis=0 then it refers columns
#here if axis=1 then it refers columns
maxv=np.amax(a)
minv=np.amin(a)
colmax=np.amax(a,axis=0)
rowmax=np.amax(a,axis=1)
colmin=np.amin(a,axis=0)
rowmin=np.amin(a,axis=1)
print("given matrix")
print(a)
print("---------------------------")
print("max value=",maxv)
print("min value=",minv)
print("----------------------------")
print("col max=",colmax)
print("row max=",rowmax)
print("Column Min=",colmin)
print("Row Min=",rowmin)
print("--------------------------------------")

given matrix
[[16 23 22 22]
 [22 26 15 12]
 [26 29 19 11]
 [29 23 11 11]]
---------------------------
max value= 29
min value= 11
----------------------------
col max= [29 29 22 22]
row max= [23 26 29 29]
Column Min= [16 23 11 11]
Row Min= [16 12 11 11]
--------------------------------------


In [29]:
#Find the mean on ndarray by using mean()--1-Dim
a=np.array([3,1,2,4])
m=np.mean(a)
print("mean({})={}".format(a,m))

mean([3 1 2 4])=2.5


In [37]:
#our won mean (average)
s=0
for v in a:
    s=s+v
print("sum=",s)
print("mean({})={}".format(a,s/len(a)))

sum= 10
mean([3 1 2 4])=2.5


In [41]:
#find the mean for col and row
a=np.array([3,1,2,4]).reshape(2,2)
print("---------------------")
print("matrix -A")
print(a)
print("-------------")
m=np.mean(a)
cm=np.mean(a,axis=0)
rm=np.mean(a,axis=1)
print("mean/n{}={}".format(a,m))
print("col mean/n ({})={}".format(a,cm))
print("row mean/n ({})={}".format(a,rm))

---------------------
matrix -A
[[3 1]
 [2 4]]
-------------
mean/n[[3 1]
 [2 4]]=2.5
col mean/n ([[3 1]
 [2 4]])=[2.5 2.5]
row mean/n ([[3 1]
 [2 4]])=[2. 3.]


In [57]:
a=np.random.randint(10,44,size=(4,4))
print("mean of a matrix ")
print(a,"------->the amean of the matrix",np.mean(a))
print("mean of col")
cm=np.mean(a,axis=0)
print("the mean of cm",cm)
print("mean of row")
rm=np.mean(a,axis=1)
print("the mean of cm",rm)

mean of a matrix 
[[43 43 17 22]
 [24 27 15 33]
 [32 31 40 16]
 [34 27 15 42]] ------->the amean of the matrix 28.8125
mean of col
the mean of cm [33.25 32.   21.75 28.25]
mean of row
the mean of cm [31.25 24.75 29.75 29.5 ]


In [59]:
#Find the median of ndarray--1-Dim with ODD Number of Elements
a=np.array([10,2,14,3,18,20,5])
print("----------------------------------")
print("Content of a")
print(a)
print("----------------------------------")
m=np.median(a)
print("Median({})={}".format(a,m))
print("----------------------------------")

----------------------------------
Content of a
[10  2 14  3 18 20  5]
----------------------------------
Median([10  2 14  3 18 20  5])=10.0
----------------------------------


In [61]:
#Find the median of ndarray--1-Dim with Even Number of Elements
a=np.array([10,2,14,3,18,20,5,6])
print("----------------------------------")
print("Content of a")
print(a)
print("----------------------------------")
m=np.median(a)
print("Median({})={}".format(a,m))
print("----------------------------------")

----------------------------------
Content of a
[10  2 14  3 18 20  5  6]
----------------------------------
Median([10  2 14  3 18 20  5  6])=8.0
----------------------------------


In [67]:
#find the meadin of ndarray---1d -dim with even number of elements
a=np.random.randint(10,20,size=(4,4))
print(a)
print("median")
cm=np.median(a,axis=0)
rm=np.median(a,axis=1)
print("col meadian/n({})={}".format(a,cm))
print("row meadian/n({})={}".format(a,rm))

[[[19 11 15 19]
  [19 10 15 13]
  [11 11 18 11]
  [10 12 11 12]]

 [[10 10 19 13]
  [16 16 13 11]
  [19 15 17 14]
  [18 10 18 18]]]
median
col meadian/n([[[19 11 15 19]
  [19 10 15 13]
  [11 11 18 11]
  [10 12 11 12]]

 [[10 10 19 13]
  [16 16 13 11]
  [19 15 17 14]
  [18 10 18 18]]])=[[14.5 10.5 17.  16. ]
 [17.5 13.  14.  12. ]
 [15.  13.  17.5 12.5]
 [14.  11.  14.5 15. ]]
row meadian/n([[[19 11 15 19]
  [19 10 15 13]
  [11 11 18 11]
  [10 12 11 12]]

 [[10 10 19 13]
  [16 16 13 11]
  [19 15 17 14]
  [18 10 18 18]]])=[[15.  11.  15.  12.5]
 [17.  12.5 17.5 13.5]]


In [69]:
#Finding Variance by using var()
a=np.array([3,1,2,4])
print("Content of a")
print(a)
v=np.var(a)
print("Variance=",v)

Content of a
[3 1 2 4]
Variance= 1.25


In [71]:
#Find Col and Row-wise variance
a=np.array([3,1,2,4]).reshape(2,2)
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
v=np.var(a)
print("Variance=",v)
cv=np.var(a,axis=0)
rv=np.var(a,axis=1)
print("Col Var=",cv)
print("Row Var=",rv)
print("------------------------------------")

------------------------------------
Content of a
[[3 1]
 [2 4]]
------------------------------------
Variance= 1.25
Col Var= [0.25 2.25]
Row Var= [1. 1.]
------------------------------------


In [74]:
#Find Col and Row-wise variance
a=np.arange(4*3).reshape(4,3)
print("------------------------------------")
print("Content of a")
print(a)
print("------------------------------------")
v=np.var(a)
print("Variance=",v)
cv=np.var(a,axis=0)
rv=np.var(a,axis=1)
print("Col Var=",cv)
print("Row Var=",rv)
print("------------------------------------")

------------------------------------
Content of a
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------------
Variance= 11.916666666666666
Col Var= [11.25 11.25 11.25]
Row Var= [0.66666667 0.66666667 0.66666667 0.66666667]
------------------------------------
