In [1]:
# in numpy there are diffrent types of the summ there are sum(),cumsum
import numpy as np
a=np.array([10,20,30,40,50,70])
print("1-d array")
print("sum operation")
a=np.sum(a)
print(a)

1-d array
sum operation
220


In [3]:
import numpy as np
a=np.array([10,20,30,40,50,70])
print("1-d array")
print("cum-sum operation")
a=np.cumsum(a)
print(a)

1-d array
sum operation
[ 10  30  60 100 150 220]


In [9]:
#now we are performing the sum,cum on 2-d array here axis=0---col  we are performing the sum of col 
a=np.array([10,20,30,88,36,14]).reshape(2,3)
print("content of a")
print(a)
print("sum of the ad array")
a=np.sum(a,axis=0)
print(a)

content of a
[[10 20 30]
 [88 36 14]]
sum of the ad array
[98 56 44]


In [11]:
#now we are performing the sum,cum on 2-d array here axis=1---row  we are performing the sum of row
a=np.array([10,20,30,88,36,14]).reshape(2,3)
print("content of a")
print(a)
print("sum of the ad array")
a=np.sum(a,axis=1)
print(a)

content of a
[[10 20 30]
 [88 36 14]]
sum of the ad array
[ 60 138]


In [17]:
#now we are performing the sum,cum on 2-d array here axis=0---col  we are performing the cumsum of col 
a=np.array([10,20,30,88,36,14]).reshape(2,3)
print("content of a")
print(a)
print("cumsum of the ad array")
a=np.cumsum(a,axis=0)
print(a)

content of a
[[10 20 30]
 [88 36 14]]
cumsum of the ad array
[[10 20 30]
 [98 56 44]]


In [19]:
#now we are performing the sum,cum on 2-d array here axis=1---row  we are performing the cumsum of row
a=np.array([10,20,30,88,36,14]).reshape(2,3)
print("content of a")
print(a)
print("cumsum of the ad array")
a=np.cumsum(a,axis=1)
print(a)

content of a
[[10 20 30]
 [88 36 14]]
cumsum of the ad array
[[ 10  30  60]
 [ 88 124 138]]
