In [11]:
#there are different types of the porduct in nd array
#pord(),cumpord()--->axis=0 col,axis=1--->row
import numpy as np
a=np.array([10,20,40,55])
print("content of a")
print(a)
print("product of a")
a=np.prod(a)
print(a)
print("cumlative product of a")
b=np.cumprod(b)
print(b)

content of a
[10 20 40 55]
product of a
440000
cumlative product of a
[440000]


In [24]:
#some more example 
a=np.array([10,20,30,40,50])
b=np.array([10,20,30,40,50])
c=np.prod([a,b],axis=0)
print(c)
c=np.prod([a,b],axis=1)
print(c)

[ 100  400  900 1600 2500]
[12000000 12000000]


In [ ]:
#now we are performig the 2d array of product

In [46]:
import numpy as np
a=np.random.randint(10,20,size=(2,3))
print(a)
print("product of a")
a=np.prod(a,axis=0)
print(a)
print("row prod")
b=np.prod([a],axis=1)
print(b)

[[19 11 11]
 [13 17 17]]
product of a
[247 187 187]
row prod
[8637343]


In [50]:
import numpy as np
a=np.random.randint(10,20,size=(2,3))
print(a)
print("cumproduct of a")
a=np.cumprod(a,axis=0)
print(a)
print("row prod")
b=np.cumprod([a],axis=1)
print(b)

[[11 14 13]
 [11 15 18]]
cumproduct of a
[[ 11  14  13]
 [121 210 234]]
row prod
[[[  11   14   13]
  [1331 2940 3042]]]
