In [9]:
#numpy.arange(Value)----------------> 0 to Value-1 with Default Step     +1
#genarte range of values from 0 to 10
import numpy as np
a=np.arange(6,dtype=float)
print("-"*50)
print("content of a=",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a= [0. 1. 2. 3. 4. 5.]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 1
Shape of a= (6,)
Size of a= 6
--------------------------------------------------


In [11]:
a.shape=(3,2)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)


--------------------------------------------------
content of a
 [[0. 1.]
 [2. 3.]
 [4. 5.]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 2
Shape of a= (3, 2)
Size of a= 6
--------------------------------------------------


In [13]:
#Generate the range of values as 10 12 14 16 18 20 22 24 26 with Matrix Format
a=np.arange(10,27,2,dtype=float) # 
print("-"*50)
a.shape=(3,3)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[10. 12. 14.]
 [16. 18. 20.]
 [22. 24. 26.]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 2
Shape of a= (3, 3)
Size of a= 9
--------------------------------------------------


In [15]:
#Generate the range of values as 10 12 14 16 18 20 22 24 26 with Matrix Format
a=np.arange(10,27,0.5,dtype=float) # 
print("-"*50)
#a.shape=(3,3)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 1
Shape of a= (34,)
Size of a= 34
--------------------------------------------------


In [17]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with Matrix Format
a=np.arange(10,15,0.25,dtype=float) # 
print("-"*50)
#a.shape=(3,3)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [10.   10.25 10.5  10.75 11.   11.25 11.5  11.75 12.   12.25 12.5  12.75
 13.   13.25 13.5  13.75 14.   14.25 14.5  14.75]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 1
Shape of a= (20,)
Size of a= 20
--------------------------------------------------


In [19]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with Matrix Format
a=np.arange(10,15,0.25,dtype=float) # 
print("-"*50)
a.shape=(4,5)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[10.   10.25 10.5  10.75 11.  ]
 [11.25 11.5  11.75 12.   12.25]
 [12.5  12.75 13.   13.25 13.5 ]
 [13.75 14.   14.25 14.5  14.75]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 2
Shape of a= (4, 5)
Size of a= 20
--------------------------------------------------


In [21]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with Matrix Format
a=np.arange(10,15,0.25,dtype=float).reshape(5,4)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[10.   10.25 10.5  10.75]
 [11.   11.25 11.5  11.75]
 [12.   12.25 12.5  12.75]
 [13.   13.25 13.5  13.75]
 [14.   14.25 14.5  14.75]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 2
Shape of a= (5, 4)
Size of a= 20
--------------------------------------------------


In [23]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with 3-D Matrix Format
a=np.arange(10,15,0.25,dtype=float).reshape(2,5,2)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[[10.   10.25]
  [10.5  10.75]
  [11.   11.25]
  [11.5  11.75]
  [12.   12.25]]

 [[12.5  12.75]
  [13.   13.25]
  [13.5  13.75]
  [14.   14.25]
  [14.5  14.75]]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 3
Shape of a= (2, 5, 2)
Size of a= 20
--------------------------------------------------


In [25]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with 3-D Matrix Format
a=np.arange(10,15,0.25,dtype=float).reshape(2,2,5)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[[10.   10.25 10.5  10.75 11.  ]
  [11.25 11.5  11.75 12.   12.25]]

 [[12.5  12.75 13.   13.25 13.5 ]
  [13.75 14.   14.25 14.5  14.75]]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 3
Shape of a= (2, 2, 5)
Size of a= 20
--------------------------------------------------


In [49]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with 3-D Matrix Format
a=np.zeros(9).reshape(3,3)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 2
Shape of a= (3, 3)
Size of a= 9
--------------------------------------------------


In [39]:
#Generate the range of values as 10 to 15 with Interval value 0.25 with 3-D Matrix Format
a=np.zeros((2,3,3),dtype=float)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 3
Shape of a= (2, 3, 3)
Size of a= 18
--------------------------------------------------


In [43]:
a=np.ones((2,3,3),dtype=float)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 3
Shape of a= (2, 3, 3)
Size of a= 18
--------------------------------------------------


In [45]:
a=np.ones((3,3),dtype=float)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 2
Shape of a= (3, 3)
Size of a= 9
--------------------------------------------------


In [47]:
a=np.full((2,3,3),5,dtype=float)
print("-"*50)
print("content of a\n",a)
print("type of a=",type(a))
print("Values type of a=",a.dtype)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
 [[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]
type of a= <class 'numpy.ndarray'>
Values type of a= float64
Dimension of a= 3
Shape of a= (2, 3, 3)
Size of a= 18
--------------------------------------------------


In [3]:
import numpy as np 
a=np.linspace(10,11)
print("content of a",a)
print("a",type(a))

content of a [10.         10.02040816 10.04081633 10.06122449 10.08163265 10.10204082
 10.12244898 10.14285714 10.16326531 10.18367347 10.20408163 10.2244898
 10.24489796 10.26530612 10.28571429 10.30612245 10.32653061 10.34693878
 10.36734694 10.3877551  10.40816327 10.42857143 10.44897959 10.46938776
 10.48979592 10.51020408 10.53061224 10.55102041 10.57142857 10.59183673
 10.6122449  10.63265306 10.65306122 10.67346939 10.69387755 10.71428571
 10.73469388 10.75510204 10.7755102  10.79591837 10.81632653 10.83673469
 10.85714286 10.87755102 10.89795918 10.91836735 10.93877551 10.95918367
 10.97959184 11.        ]
a <class 'numpy.ndarray'>


In [9]:
import numpy as np 
a=np.linspace(10,11,endpoint=True)
print("content of a",a)
print("a",type(a))

content of a [10.         10.02040816 10.04081633 10.06122449 10.08163265 10.10204082
 10.12244898 10.14285714 10.16326531 10.18367347 10.20408163 10.2244898
 10.24489796 10.26530612 10.28571429 10.30612245 10.32653061 10.34693878
 10.36734694 10.3877551  10.40816327 10.42857143 10.44897959 10.46938776
 10.48979592 10.51020408 10.53061224 10.55102041 10.57142857 10.59183673
 10.6122449  10.63265306 10.65306122 10.67346939 10.69387755 10.71428571
 10.73469388 10.75510204 10.7755102  10.79591837 10.81632653 10.83673469
 10.85714286 10.87755102 10.89795918 10.91836735 10.93877551 10.95918367
 10.97959184 11.        ]
a <class 'numpy.ndarray'>


In [29]:
import numpy as np 
a,vi=np.linspace(10,11,num=6,endpoint=True,retstep=True)
print("content of a",a)
print("a",type(a))
print("val of rat step",vi)

content of a [10.  10.2 10.4 10.6 10.8 11. ]
a <class 'numpy.ndarray'>
val of rat step 0.2


In [5]:
import numpy as np
lst=[1,0,0,1]
a=np.array(lst)
a.shape=(2,2)
print("unit Matrix")
print(a)

unit Matrix
[[1 0]
 [0 1]]


In [7]:
#convert 2D into 1 D
a.shape=(9,)
print("Unit Matrix in 1-D")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

ValueError: cannot reshape array of size 4 into shape (9,)

In [9]:
#Create ndarray object with 3x 3 identity OR Unit Matrix
import numpy as np
a=np.identity(3,dtype=int)
print("Unit Matrix")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

Unit Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dim of a= 2
Shape of a= (3, 3)


In [17]:
#convert 2D into 1 D
a.shape=(3,3)
print("Unit Matrix in 1-D")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

Unit Matrix in 1-D
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dim of a= 2
Shape of a= (3, 3)


In [1]:
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
import numpy as np
a=np.eye(6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [11]:
import numpy as np
a=np.eye(6,k=-2,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


In [13]:
import numpy as np
a=np.eye(6,k=-1,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [15]:
import numpy as np
a=np.eye(6,k=0,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [17]:
import numpy as np
a=np.eye(6,k=1,dtype=int)
print(a)

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


In [19]:
import numpy as np
a=np.eye(6,k=2,dtype=int)
print(a)

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [21]:
import numpy as np
a=np.eye(6,k=4,dtype=int)
print(a)

[[0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [23]:
import numpy as np
a=np.eye(6,15,k=-2,dtype=int)
print(a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]


In [25]:
import numpy as np
a=np.eye(6,15,k=1,dtype=int)
print(a)

[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]


In [27]:
 import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print(a)
b=np.array([[1,2],[3,4]])
print(b)

[[10 20 30]
 [40 50 60]]
[[1 2]
 [3 4]]


In [29]:
c=np.hstack((b,a))
print(c)

[[ 1  2 10 20 30]
 [ 3  4 40 50 60]]


In [31]:
#Example
a=np.arange(9).reshape(3,3)
b=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("---------------------------------")
print("Array1")
print(a)
print("---------------------------------")
print("Array2")
print(b)
print("---------------------------------")

---------------------------------
Array1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------------------------
Array2
[[10 20 30]
 [40 50 60]
 [70 80 90]]
---------------------------------


In [33]:
#merge array1 and array2 in array3
c=np.hstack((a,b))
print("Merged Array")
print(c)
print("---------------------------------")


Merged Array
[[ 0  1  2 10 20 30]
 [ 3  4  5 40 50 60]
 [ 6  7  8 70 80 90]]
---------------------------------


In [35]:

#merge array1 and array2 in array3
c=np.vstack((a,b))
print("Merged Array")
print(c)
print("---------------------------------")

Merged Array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
---------------------------------


In [37]:
#Syntax:  varname=numpy.vstack((ndarray1,ndarray2))
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print("---------------------------------")
print("Array1")
print(a)
print("---------------------------------")
b=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("Array2")
print(b)
print("---------------------------------")

---------------------------------
Array1
[[10 20 30]
 [40 50 60]]
---------------------------------
Array2
[[1 2 3]
 [3 4 5]
 [6 7 8]]
---------------------------------


In [39]:
#merge array1 and array2 in array3 vertically
c=np.vstack((a,b))
print("Merged Array")
print(c)
print("---------------------------------")

Merged Array
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]]
---------------------------------


In [41]:
#merge array1 and array2 in array3 vertically
d=np.vstack((b,a))
print("Merged Array")
print(d)
print("---------------------------------")

Merged Array
[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [10 20 30]
 [40 50 60]]
---------------------------------
