In [1]:
#random module of numpy 
#randint(),rand(),unifrom(),rand(),normal(),shuffle(),choice()

In [3]:
import numpy.random as nr
a=nr.randint(3)
print(a)

0


In [11]:
a=nr.randint(3,100)
print(a)

34


In [21]:
a=nr.randint(3,100,size=5)
print(a)

[59 46  9  6 99]


In [29]:
import numpy.random as nr
a=nr.randint(3,100,size=(2,3,4))
print(a)
print(a.shape)
print(a.ndim)
print(type(a),a.dtype)

[[[34 93  6 71]
  [48 60 84 27]
  [28 67 32 10]]

 [[95 29 71 61]
  [12 59 78 12]
  [28 62 31 95]]]
(2, 3, 4)
3
<class 'numpy.ndarray'> int32


In [31]:
a=nr.rand(5)
print(a)

[0.69636029 0.51975141 0.54366103 0.01370554 0.05500806]


In [33]:
a=nr.rand(1)
print(a)

[0.35587134]


In [43]:
a=nr.rand(5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)

[0.60463677 0.01038916 0.79894013 0.3067396  0.33540404] the dimension is= 1
<class 'numpy.ndarray'> float64


In [45]:
a=nr.rand(3,5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)

[[0.3633146  0.7373183  0.75882707 0.28865896 0.0282419 ]
 [0.23955891 0.4878744  0.56484978 0.16207759 0.31123202]
 [0.27384945 0.65151072 0.80152341 0.27688448 0.92513292]] the dimension is= 2
<class 'numpy.ndarray'> float64


In [47]:
a=nr.rand(2,3,5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)

[[[0.09732936 0.15166604 0.95394015 0.67255668 0.202586  ]
  [0.84390823 0.83072295 0.20556849 0.1914388  0.82821653]
  [0.39853922 0.01271931 0.38847064 0.99550427 0.58963158]]

 [[0.3369694  0.38749618 0.12965038 0.87179696 0.63420302]
  [0.67992636 0.47572228 0.16392226 0.08550085 0.01989175]
  [0.66697532 0.4224215  0.00374668 0.4400353  0.98595543]]] the dimension is= 3
<class 'numpy.ndarray'> float64


In [71]:
a=nr.rand(2,4,5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)
for s in range(len(a[0])):
    for s1 in range(len(a[0])):
        print(s,s1,end="")
    print()
    

[[[0.77184929 0.31262299 0.68331546 0.17409765 0.46897529]
  [0.23335072 0.95868042 0.50057014 0.27569119 0.50898376]
  [0.51876361 0.1980502  0.88952176 0.9319254  0.203578  ]
  [0.22186303 0.58990554 0.45043388 0.22702011 0.82670265]]

 [[0.52487645 0.45740215 0.83476841 0.84087008 0.3912763 ]
  [0.52441182 0.3813744  0.22333214 0.27012864 0.82446354]
  [0.67272313 0.13958024 0.24742421 0.59859383 0.31400992]
  [0.93679894 0.6623751  0.74793942 0.91049111 0.34809514]]] the dimension is= 3
<class 'numpy.ndarray'> float64
0 00 10 20 3
1 01 11 21 3
2 02 12 22 3
3 03 13 23 3


In [73]:
#unifrom
import numpy.random as r
uv=r.uniform()
print(uv)

0.8062552778743464


In [75]:
import numpy.random as r
uv=r.uniform(10,11)
print(uv)

10.615339534057936


In [77]:
import numpy.random as r
uv=r.uniform(10,11,size=5)
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)

[10.72918143 10.93647102 10.77054904 10.0424127  10.99288266]
the dimension= 1
type= <class 'numpy.ndarray'>
size= 5


In [79]:
import numpy.random as r
uv=r.uniform(10,11,size=5)
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)
print("dtype=",uv.dtype)
print("shape=",uv.shape)

[10.02536533 10.02975489 10.52027487 10.50844662 10.37627402]
the dimension= 1
type= <class 'numpy.ndarray'>
size= 5
dtype= float64
shape= (5,)


In [83]:
import numpy.random as r
uv=r.uniform(10,11,size=(3,5))
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)
print("dtype=",uv.dtype)
print("shape=",uv.shape)

[[10.14867376 10.8917266  10.37436874 10.26345682 10.89385455]
 [10.64927277 10.87128766 10.9242703  10.35485969 10.86198845]
 [10.51978583 10.17750028 10.00683955 10.87690795 10.20570621]]
the dimension= 2
type= <class 'numpy.ndarray'>
size= 15
dtype= float64
shape= (3, 5)


In [85]:
import numpy.random as r
uv=r.uniform(10,11,size=(2,3,5))
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)
print("dtype=",uv.dtype)
print("shape=",uv.shape)

[[[10.61347634 10.1883313  10.87606083 10.37051116 10.3957573 ]
  [10.89631448 10.81111369 10.26449746 10.47085791 10.45641577]
  [10.89632252 10.92389169 10.45695636 10.41585502 10.34103174]]

 [[10.85174821 10.80709781 10.67616467 10.19148144 10.25354671]
  [10.09924545 10.24360599 10.91607233 10.81450356 10.85403141]
  [10.86890369 10.53661843 10.36343452 10.70842494 10.50309835]]]
the dimension= 3
type= <class 'numpy.ndarray'>
size= 30
dtype= float64
shape= (2, 3, 5)


In [3]:
#Syntax-1: numpy.random.randn()
#Syntax-2: numpy.random.randn(value)
#Generating Number of Random floating Values (Value times) 
#for standard Normal Distribution and either +ve or -ve
import numpy.random as r
rv=r.randn()
print(rv)


-0.7056363659786561


In [7]:
rv=r.randn(10,12)
print(rv)
print("dimension of rv",rv.ndim)
print("size=",rv.size)
print("type",type(rv),rv.dtype)


[[-0.71958092 -1.61453859 -0.51206884  0.00873229 -2.19602705 -0.03392785
   1.21908732  0.08568062 -1.30155007  1.24142994  0.0476506   0.16962588]
 [ 0.90072465  1.29632776  0.51329423  1.40085118 -1.0619274   0.29351742
   1.21996002  0.7533987  -0.53992842 -0.99163543  0.52833987  0.93592987]
 [-0.96286549 -0.77697843 -0.60455061  1.3855656  -0.24845391 -0.27529773
   2.63869045  0.53634132 -0.99435063  0.13776034  0.50295694  1.32335185]
 [-0.87886141 -2.17407795  0.25271024  2.33183164  1.03377686  0.66028926
  -0.23113562  0.81822971  0.88590485  0.32360194  0.10879906  1.45817008]
 [-0.13645402 -0.36980238 -0.17925524 -2.12513406 -2.01769098  0.07724032
   1.33707763 -1.83667441 -1.22991565  0.24652949 -1.49852155 -1.44739058]
 [-0.33151094 -0.59119348  0.75057001  1.59479463 -0.04985406  2.13300667
  -0.10470139  1.22039615 -1.09522456 -0.18422275 -0.29306482 -0.26407335]
 [-0.6883192  -1.10233931  1.44343843 -0.426027   -0.51044661  0.93089711
  -1.41797428  0.8732686  -0.784

In [21]:
rv=r.randn(3,2,3)
print(rv)
print("dimension of rv",rv.ndim)
print("size=",rv.size,rv.shape)
print("type",type(rv),rv.dtype)

[[[-0.41549209 -0.43450124 -0.16463916]
  [ 0.97986334  1.3051173  -0.3079383 ]]

 [[-0.11500247  0.65855871 -0.07193419]
  [-0.62330827  0.4621535   1.11786121]]

 [[-1.19326422  0.1746324  -1.20423326]
  [ 0.30673726 -1.4991644  -0.14415653]]]
dimension of rv 3
size= 18 (3, 2, 3)
type <class 'numpy.ndarray'> float64


In [23]:
for mn in range(len(rv)):
    for rn in range(len(rv[0])):
        for rk in range(len(rv[0])):
            print(round(rv[mn,rn,rk],2),end="\t")
        print()
    print()

-0.42	-0.43	
0.98	1.31	

-0.12	0.66	
-0.62	0.46	

-1.19	0.17	
0.31	-1.5	



In [27]:
#Syntax-1: numpy.random.normal()
#Syntax-2: numpy.random.normal(loc=0.0,scale=1.0)
import numpy.random as r
rv=r.normal()
print(rv)

1.3544793414529719


In [41]:
import numpy.random as r
rv=r.normal(2,5)
print(rv)

-0.9771468387824123


In [39]:
import numpy.random as r
rv=r.normal(2,5,size=5)
print(rv)
print("shape=",rv.shape)
print("the dimension =",rv.ndim)

[ 3.75951746  4.19884769 -0.2642693   4.75139052  8.43647244]
shape= (5,)
the dimension = 1


In [47]:
import numpy.random as r
rv=r.normal(2,5,size=(2,3))
print(rv)
print("shape=",rv.shape)
print("the dimension =",rv.ndim)

[[ 1.68042449 -8.86089573 -3.5834118 ]
 [-1.46297103  0.98527959 -1.31468188]]
shape= (2, 3)
the dimension = 2


In [49]:
import numpy.random as r
rv=r.normal(2,5,size=(2,3,6))
print(rv)
print("shape=",rv.shape)
print("the dimension =",rv.ndim)

[[[-1.85706594  4.7005475   1.36766328 -4.52685775  8.95234601
    1.4555623 ]
  [ 5.18643064  3.48769533  6.03597428  6.08510173  0.86911097
   -1.61890453]
  [ 2.95794629  5.94268518  6.30160409 10.58812805  0.87545078
   -1.95606179]]

 [[-1.06115387  5.07495392  1.4818702  -4.6873691  -0.23092688
   -2.74457881]
  [ 1.94818495 -0.99707717  1.27489885 -2.33649798  6.05800124
   -2.67670073]
  [-0.77179244  5.34800322 -1.79279193  4.06361312  0.30510557
   -1.80649619]]]
shape= (2, 3, 6)
the dimension = 3


In [53]:
import numpy as np 
import numpy.random as r
a=np.array([10,20,50,40,60,80])
print(a)
print(a,type(a))

[10 20 50 40 60 80]
[10 20 50 40 60 80] <class 'numpy.ndarray'>


In [63]:
cv=r.choice(a)
print(cv)
print(cv,type(cv))

60
60 <class 'numpy.int32'>


In [65]:
a=np.array(list("python"))
cv=r.choice(a)
print(cv)

n


In [72]:
cv=r.choice(np.array(list("1234567890abcdfeghijklmnopqrstuvwxyzABCDFEGHIJKLMNOPQRSTUVWXYZ")))
print(cv,type(cv))

W <class 'numpy.str_'>


In [74]:
a=np.array([10,20,30,40,50])
cv=r.choice(a,size=5)
print(cv)

[10 20 30 50 20]


In [76]:
a=np.array([10,20,30,40,50])
cv=r.choice(a,size=(2,3))
print(cv)

[[10 50 10]
 [20 10 50]]


In [78]:
a=np.array([10,20,30,40,50])
cv=r.choice(a,size=(3,2,3))
print(cv)

[[[30 10 20]
  [20 40 50]]

 [[10 20 40]
  [20 10 10]]

 [[10 30 10]
  [30 40 20]]]


In [20]:
import numpy as np
import random as r

# Randomly selecting from predefined lists
state_code = r.choice(["TS", "AP", "MH", "KA", "TN"])
district_num = str(r.randint(0, 99)).zfill(2)  # Ensure two digits
letters = ''.join(r.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ") for _ in range(2))
number = str(r.randint(0, 9999)).zfill(4)  # Ensure four digits

# Combine all parts
print("Bike Plate Number =", state_code,district_num,letters,number)


Bike Plate Number = TS 66 PQ 5507


In [3]:
import numpy as np
from numpy import random as r
a=np.arange(10)
print("Original Content of ndarray")
print(a)
print("----------------------------------------")
r.shuffle(a)
print("Shuffled  Content of ndarray")
print(a)

Original Content of ndarray
[0 1 2 3 4 5 6 7 8 9]
----------------------------------------
Shuffled  Content of ndarray
[1 9 8 2 7 3 4 5 0 6]


In [5]:
a=np.arange(10)
print("Original Content of ndarray")
print(a,id(a))
print("----------------------------------------")
r.shuffle(a)
print("Shuffled  Content of ndarray")
print(a,id(a))

Original Content of ndarray
[0 1 2 3 4 5 6 7 8 9] 1928185447792
----------------------------------------
Shuffled  Content of ndarray
[3 7 1 0 4 9 5 8 2 6] 1928185447792


In [8]:
#what are various shuffled Values of ndarray
a=np.arange(10)
print("Original Content of ndarray")
print(a)
print("----------------------------------------")
for i in range(1,len(a)+1):
    r.shuffle(a)
    print("Combination:{}-->{}".format(i,a))
print("----------------------------------------")

Original Content of ndarray
[0 1 2 3 4 5 6 7 8 9]
----------------------------------------
Combination:1-->[4 5 7 2 8 9 6 3 1 0]
Combination:2-->[1 8 9 3 5 6 2 7 0 4]
Combination:3-->[2 8 3 0 5 9 6 7 4 1]
Combination:4-->[0 5 1 7 6 2 8 3 9 4]
Combination:5-->[3 0 1 4 2 8 6 9 7 5]
Combination:6-->[0 1 9 4 5 8 7 2 3 6]
Combination:7-->[1 3 9 7 4 5 2 0 8 6]
Combination:8-->[6 9 2 5 1 4 7 3 8 0]
Combination:9-->[8 3 2 0 4 6 9 1 5 7]
Combination:10-->[9 8 5 7 4 1 0 3 6 2]
----------------------------------------


In [14]:
#Shuffling 2-D Data
a=r.randint(1,101,size=(6,5))
print("----------------------------------")
print("Original Matrix")
print("----------------------------------")
print(a)
print("----------------------------------")
print("ReShuffled  Matrix")
print("----------------------------------")
r.shuffle(a)
print(a)
print("----------------------------------")

----------------------------------
Original Matrix
----------------------------------
[[82 87 66 18 45]
 [ 1  8 50 83 41]
 [17 93 24 57 43]
 [54 54 56 96 47]
 [87 26 42 73 10]
 [61 67 30 78 20]]
----------------------------------
ReShuffled  Matrix
----------------------------------
[[ 1  8 50 83 41]
 [17 93 24 57 43]
 [87 26 42 73 10]
 [61 67 30 78 20]
 [54 54 56 96 47]
 [82 87 66 18 45]]
----------------------------------


In [16]:
#Another Function for Re-arranging th Elements--permutation()
a=np.array([10,20,30,40,50,60,70])
print("Original array before permutation")
print(a)
print("-------------------------------")
b=r.permutation(a)
print("ReShuffled  Array")
print(b)
print("-------------------------------")
print("Original array after permutation")

Original array before permutation
[10 20 30 40 50 60 70]
-------------------------------
ReShuffled  Array
[70 20 40 30 50 10 60]
-------------------------------
Original array after permutation


In [18]:
a=np.array([10,20,30,40,50,60,70])
print("Original array before permutation")
print(a)
print("-------------------------------")
b=r.shuffle(a)
print("Val of b=",b)
print("-------------------------------")
print("Original array after Shuffle")
print(a)

Original array before permutation
[10 20 30 40 50 60 70]
-------------------------------
Val of b= None
-------------------------------
Original array after Shuffle
[40 30 70 60 50 10 20]
