In [1]:
#random module of numpy 
#randint(),rand(),unifrom(),rand(),normal(),shuffle(),choice()

In [3]:
import numpy.random as nr
a=nr.randint(3)
print(a)

0


In [11]:
a=nr.randint(3,100)
print(a)

34


In [21]:
a=nr.randint(3,100,size=5)
print(a)

[59 46  9  6 99]


In [29]:
import numpy.random as nr
a=nr.randint(3,100,size=(2,3,4))
print(a)
print(a.shape)
print(a.ndim)
print(type(a),a.dtype)

[[[34 93  6 71]
  [48 60 84 27]
  [28 67 32 10]]

 [[95 29 71 61]
  [12 59 78 12]
  [28 62 31 95]]]
(2, 3, 4)
3
<class 'numpy.ndarray'> int32


In [31]:
a=nr.rand(5)
print(a)

[0.69636029 0.51975141 0.54366103 0.01370554 0.05500806]


In [33]:
a=nr.rand(1)
print(a)

[0.35587134]


In [43]:
a=nr.rand(5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)

[0.60463677 0.01038916 0.79894013 0.3067396  0.33540404] the dimension is= 1
<class 'numpy.ndarray'> float64


In [45]:
a=nr.rand(3,5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)

[[0.3633146  0.7373183  0.75882707 0.28865896 0.0282419 ]
 [0.23955891 0.4878744  0.56484978 0.16207759 0.31123202]
 [0.27384945 0.65151072 0.80152341 0.27688448 0.92513292]] the dimension is= 2
<class 'numpy.ndarray'> float64


In [47]:
a=nr.rand(2,3,5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)

[[[0.09732936 0.15166604 0.95394015 0.67255668 0.202586  ]
  [0.84390823 0.83072295 0.20556849 0.1914388  0.82821653]
  [0.39853922 0.01271931 0.38847064 0.99550427 0.58963158]]

 [[0.3369694  0.38749618 0.12965038 0.87179696 0.63420302]
  [0.67992636 0.47572228 0.16392226 0.08550085 0.01989175]
  [0.66697532 0.4224215  0.00374668 0.4400353  0.98595543]]] the dimension is= 3
<class 'numpy.ndarray'> float64


In [71]:
a=nr.rand(2,4,5)
print(a,"the dimension is=",a.ndim)
print(type(a),a.dtype)
for s in range(len(a[0])):
    for s1 in range(len(a[0])):
        print(s,s1,end="")
    print()
    

[[[0.77184929 0.31262299 0.68331546 0.17409765 0.46897529]
  [0.23335072 0.95868042 0.50057014 0.27569119 0.50898376]
  [0.51876361 0.1980502  0.88952176 0.9319254  0.203578  ]
  [0.22186303 0.58990554 0.45043388 0.22702011 0.82670265]]

 [[0.52487645 0.45740215 0.83476841 0.84087008 0.3912763 ]
  [0.52441182 0.3813744  0.22333214 0.27012864 0.82446354]
  [0.67272313 0.13958024 0.24742421 0.59859383 0.31400992]
  [0.93679894 0.6623751  0.74793942 0.91049111 0.34809514]]] the dimension is= 3
<class 'numpy.ndarray'> float64
0 00 10 20 3
1 01 11 21 3
2 02 12 22 3
3 03 13 23 3


In [73]:
#unifrom
import numpy.random as r
uv=r.uniform()
print(uv)

0.8062552778743464


In [75]:
import numpy.random as r
uv=r.uniform(10,11)
print(uv)

10.615339534057936


In [77]:
import numpy.random as r
uv=r.uniform(10,11,size=5)
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)

[10.72918143 10.93647102 10.77054904 10.0424127  10.99288266]
the dimension= 1
type= <class 'numpy.ndarray'>
size= 5


In [79]:
import numpy.random as r
uv=r.uniform(10,11,size=5)
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)
print("dtype=",uv.dtype)
print("shape=",uv.shape)

[10.02536533 10.02975489 10.52027487 10.50844662 10.37627402]
the dimension= 1
type= <class 'numpy.ndarray'>
size= 5
dtype= float64
shape= (5,)


In [83]:
import numpy.random as r
uv=r.uniform(10,11,size=(3,5))
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)
print("dtype=",uv.dtype)
print("shape=",uv.shape)

[[10.14867376 10.8917266  10.37436874 10.26345682 10.89385455]
 [10.64927277 10.87128766 10.9242703  10.35485969 10.86198845]
 [10.51978583 10.17750028 10.00683955 10.87690795 10.20570621]]
the dimension= 2
type= <class 'numpy.ndarray'>
size= 15
dtype= float64
shape= (3, 5)


In [85]:
import numpy.random as r
uv=r.uniform(10,11,size=(2,3,5))
print(uv)
print("the dimension=",uv.ndim)
print("type=",type(uv))
print("size=",uv.size)
print("dtype=",uv.dtype)
print("shape=",uv.shape)

[[[10.61347634 10.1883313  10.87606083 10.37051116 10.3957573 ]
  [10.89631448 10.81111369 10.26449746 10.47085791 10.45641577]
  [10.89632252 10.92389169 10.45695636 10.41585502 10.34103174]]

 [[10.85174821 10.80709781 10.67616467 10.19148144 10.25354671]
  [10.09924545 10.24360599 10.91607233 10.81450356 10.85403141]
  [10.86890369 10.53661843 10.36343452 10.70842494 10.50309835]]]
the dimension= 3
type= <class 'numpy.ndarray'>
size= 30
dtype= float64
shape= (2, 3, 5)
