In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60,70])
print("content of a")
print(a)

contrnt of a
[10 20 30 40 50 60 70]


In [5]:
#steps for adavnce indexing on 1-d
#Step-1: Identify the Indices of Elements and taken them in Traditional object of Python or ndarray obj
#Step-2: Pass the Traditional Object OR Ndarray Object with Idices of Elements to the NDArray Object        

In [7]:
lst=[0,3,4]# or #step1--tpl=(0,3,4)
a[lst]#step2----[0,3,4]

array([10, 40, 50])

In [9]:
#OR
#Step-1: Identify the Indices of 10 40 50 
b=np.array([0,3,4]) 
#Step-2: Pass ndarray object b to ndarray object--a
a[b]

array([10, 40, 50])

In [11]:
#OR
#Examples:  I want to 10 40 50 Only by using Indexing
a[[0,3,4]]

array([10, 40, 50])

In [15]:
a[[-1,-2,1,0]]

array([70, 60, 20, 10])

In [23]:
a=np.arange(0,25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [27]:
a[[0,9,12,14,23]]

array([ 0,  9, 12, 14, 23])

In [29]:
a=np.random.randint(1,100,size=25)
print(a)

[54 90 94 29 39  8 46 91 55 42 97 32  9 47 12 82 66 26  9 98 58 56 18 20
 91]


In [35]:
for index,value in enumerate(a):
    print(index,"-------->",value)

0 --------> 54
1 --------> 90
2 --------> 94
3 --------> 29
4 --------> 39
5 --------> 8
6 --------> 46
7 --------> 91
8 --------> 55
9 --------> 42
10 --------> 97
11 --------> 32
12 --------> 9
13 --------> 47
14 --------> 12
15 --------> 82
16 --------> 66
17 --------> 26
18 --------> 9
19 --------> 98
20 --------> 58
21 --------> 56
22 --------> 18
23 --------> 20
24 --------> 91


In [37]:
a[[5,23,5]]

array([ 8, 20,  8])

In [39]:
a=np.random.randint(1,100,size=(5,5))
print(a)

[[17 68 45 35 47]
 [39 44  1 21 20]
 [71 37 65 60 85]
 [57 72  5  7 90]
 [77 78 31 38 81]]


In [45]:
a[(0,0)]

17

In [73]:
a[(0,1),(0,2)]

array([17,  1])

In [75]:
a[(0,1,2),(1,1,1)]

array([68, 44, 37])

In [77]:
a=np.random.randint(1,100,size=(5,5))
print(a)

[[40 20 74 61 90]
 [67 66  6 19 85]
 [80 91 37 41 52]
 [20 81 84 19 39]
 [79 74 68 83 97]]


In [79]:
a[(0,2,3),(2,3,4)]

array([74, 41, 39])

In [81]:
a=np.random.randint(1,100,size=(2,5,5))
print(a)

[[[49 22 20 39 53]
  [80 55 46 67  2]
  [55 60 59 41 53]
  [80 24  6 43 13]
  [84 47  3 58 97]]

 [[68 29 18 90 23]
  [48 39 88  8 21]
  [10 82 17 16  5]
  [67 26 23 57 21]
  [60 96 18 12 30]]]


In [83]:
a[[0,1],[2,4],[0,0]]

array([55, 60])