In [1]:
#basic silicing on 1d array
#syntax-1:1dndarray[start:stop:step]

In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35])
print("-"*50)
print("content of a")
print(a)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)
print("size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a
[10 20 30 40 50 60 70 80 90 15 25 35]
dimension of a= 1
shape of a= (12,)
size of a= 12
--------------------------------------------------


In [5]:
#+ve:+ve:+ve
a[0:4]

array([10, 20, 30, 40])

In [7]:
a[4:0]

array([], dtype=int32)

In [9]:
a[3:7]

array([40, 50, 60, 70])

In [11]:
#-ve :-ve:+ve
a[-12:-5]

array([10, 20, 30, 40, 50, 60, 70])

In [13]:
a[-12:-5:2]

array([10, 30, 50, 70])

In [15]:
a[:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35])

In [17]:
a[:2]

array([10, 20])

In [19]:
a[-100::2]

array([10, 30, 50, 70, 90, 25])

In [21]:
a[:100:2]

array([10, 30, 50, 70, 90, 25])

In [23]:
a[::3]

array([10, 40, 70, 15])

In [25]:
a[::-1]

array([35, 25, 15, 90, 80, 70, 60, 50, 40, 30, 20, 10])

In [27]:
a[::-2]

array([35, 15, 80, 60, 40, 20])

In [37]:
import numpy as np 
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35]).reshape(3,4)
print("-"*50)
print("content of a ")
print(a)
print("dimension of a",a.ndim)
print("sahpe of a=",a.shape)
print("size of a=",a.size)
print("-"*50)

--------------------------------------------------
content of a 
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]]
dimension of a 2
sahpe of a= (3, 4)
size of a= 12
--------------------------------------------------


In [41]:
a[0:3:2,0:1]

array([[10],
       [90]])

In [45]:
a[::,0:2]

array([[10, 20],
       [50, 60],
       [90, 15]])

In [61]:
a[1:3:2,0:1]

array([[50]])

In [63]:
#Get 0th Column [10,50,90]
a[::1,0:1:1]

array([[10],
       [50],
       [90]])

In [65]:
# Get 1 Row to last with all Cols
a[1:,0:]

array([[50, 60, 70, 80],
       [90, 15, 25, 35]])

In [67]:
a[:2:,2::]

array([[30, 40],
       [70, 80]])

In [69]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]]


In [19]:
# N-D Array Slicing
#Syntax:NDarrayobj[MatRowBeg:MatRowEnd:MatStep,RowBegin:RowEnd:RowStep, ColBegin:ColEnd:ColStep]
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,55,65,75,12]).reshape(2,4,2)
print("contet of a")
print(a)
print("shape=",a.shape)

contet of a
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [55 65]
  [75 12]]]
shape= (2, 4, 2)


In [21]:
a[0:1,1:3,0:2]

array([[[30, 40],
        [50, 60]]])

In [23]:
a[1:,1:,0:]

array([[[25, 35],
        [55, 65],
        [75, 12]]])

In [25]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [55 65]
  [75 12]]]


In [29]:
a[:1,0:3,0:1]

array([[[10],
        [30],
        [50]]])

In [37]:
a[0:2,0:1,0:2]

array([[[10, 20]],

       [[90, 15]]])

In [39]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [55 65]
  [75 12]]]


In [41]:
a[1:,0:2,0:2]

array([[[90, 15],
        [25, 35]]])

In [45]:
# N-D Array Slicing
#Syntax:NDarrayobj[MatRowBeg:MatRowEnd:MatStep,RowBegin:RowEnd:RowStep, ColBegin:ColEnd:ColStep]
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,55,65,75,12]).reshape(2,2,2,2)
print("contet of a")
print(a)
print("shape=",a.shape)

contet of a
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 15]
   [25 35]]

  [[55 65]
   [75 12]]]]
shape= (2, 2, 2, 2)


In [57]:
a[0:1,0:1,0:1,0:2]

array([[[[10, 20]]]])

In [59]:
print(a)

[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 15]
   [25 35]]

  [[55 65]
   [75 12]]]]
