In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print("-"*50)
print("content of a")
print(a)
print("dimension of a=",a.ndim)
print("shape os a=",a.shape)
print("size of a =",a.size)
print("-"*50)


--------------------------------------------------
content of a
[10 20 30 40 50 60]
dimension of a= 1
shape os a= (6,)
size of a = 6
--------------------------------------------------


In [5]:
#get the value of 10 ndaarray obj 
a[0]

10

In [13]:
#get value of 20 from nd array object a
a[1]

20

In [11]:
a[-1]

60

In [ ]:
#Basic Indexing in 2-D(Matrix)---Obtains Single Element
#Syntax-1: ndarraytobj[RowIndex,ColIndex]
#Syntax-2: ndarraytobj[RowIndex][ColIndex]
# Here RowIndex and ColIndex can be either +ve or -ve

In [63]:
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35]).reshape(3,4)
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]]
Dimension of a= 2
Shape of a= (3, 4)
Size of a= 12
-------------------------------------------------


In [65]:
#get the element 60
a[1,1]

60

In [29]:
#get the element 20
a[-3,-3]

20

In [31]:
a[0,-3]

20

In [33]:
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35]).reshape(3,4)
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]]
Dimension of a= 2
Shape of a= (3, 4)
Size of a= 12
-------------------------------------------------


In [35]:
#get Complete Row [10,20,30,40] by using Indexing
a[0]

array([10, 20, 30, 40])

In [37]:
#get Complete Row [90,15,25,35] by using Indexing
a[2]

array([90, 15, 25, 35])

In [39]:
#get Complete Row [90,15,25,35] by using Indexing
a[-1]

array([90, 15, 25, 35])

In [67]:
#Basic Indexing in n-D(MatrixNumber, Rows, Cols)---Obtains Single Element
#Syntax-1: ndarraytobj[MatrixIndex,RowIndex,ColIndex]
#Syntax-2: ndarraytobj[MatrixIndex][RowIndex][ColIndex]
#Syntax-3: ndarraytobj[MatrixIndex,RowIndex][ColIndex]
# Here Matrix Index , RowIndex and ColIndex can be either +ve or -ve

In [69]:
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35]).reshape(2,3,2)
print("-------------------------------------------------")
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of a=",a.shape)
print("Size of a=",a.size)
print("-------------------------------------------------")

-------------------------------------------------
Content of a
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 15]
  [25 35]]]
Dimension of a= 3
Shape of a= (2, 3, 2)
Size of a= 12
-------------------------------------------------


In [71]:
#get the element 40
a[0,1,1]

40

In [81]:
#get the element 25
a[1,2,0]

25

In [83]:
#get the element 70
a[1,0,0]

70

In [85]:
#get the element 1st matrix
a[0]

array([[10, 20],
       [30, 40],
       [50, 60]])

In [87]:
#get the element 2nd matrix
a[1]

array([[70, 80],
       [90, 15],
       [25, 35]])

In [89]:
#get the element 90
a[-1,-2,-2]

90

In [ ]:
#get the element 35
a[-1,2,-1]