In [1]:
#numpy iteerating the nd array
#here we are iterating the data in 1d array
#for i in nd:
import numpy as np 
a=np.array([10,20,30,40,50,60,70,90])
print(a)

[10 20 30 40 50 60 70 90]


In [3]:
for i in a:
    print(i)

10
20
30
40
50
60
70
90


In [29]:
#here we are iterrating the 2d array
a=np.array([10,20,30,40,60,90,80,75,56]).reshape(3,3)
print("content of a")
print(a)
for i in a:
    print(i)

content of a
[[10 20 30]
 [40 60 90]
 [80 75 56]]
[10 20 30]
[40 60 90]
[80 75 56]


In [33]:
a=np.random.randint(10,20,size=(3,3))
print(a)
print("dimension of a=",a.ndim)
print("content of a")
print("shape of a=",a.shape)
#itereraing the data from 2d array
for row in a:
    for col in row:
        print(col)
print("-"*50)

[[12 10 15]
 [19 15 14]
 [17 13 18]]
dimension of a= 2
content of a
shape of a= (3, 3)
12
10
15
19
15
14
17
13
18
[12 10 15]
--------------------------------------------------


In [77]:
import numpy as np 
a=np.arange(3*3*3).reshape(3,3,3)
print(a)
print("dimension of a=",a.ndim)
#iterating the data of 3d array 
for mat in a:
    for row in mat:
        for col in mat:
            print(col)
        print("-"*50)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
dimension of a= 3
[0 1 2]
[3 4 5]
[6 7 8]
--------------------------------------------------
[0 1 2]
[3 4 5]
[6 7 8]
--------------------------------------------------
[0 1 2]
[3 4 5]
[6 7 8]
--------------------------------------------------
[ 9 10 11]
[12 13 14]
[15 16 17]
--------------------------------------------------
[ 9 10 11]
[12 13 14]
[15 16 17]
--------------------------------------------------
[ 9 10 11]
[12 13 14]
[15 16 17]
--------------------------------------------------
[18 19 20]
[21 22 23]
[24 25 26]
--------------------------------------------------
[18 19 20]
[21 22 23]
[24 25 26]
--------------------------------------------------
[18 19 20]
[21 22 23]
[24 25 26]
--------------------------------------------------


In [83]:
#nditer()
import numpy as np
a=np.arange(50,61)
print(a)
#iterring the data from 1d array 
#uding nditer()
for val in np.nditer(a):
    print(val)

[50 51 52 53 54 55 56 57 58 59 60]
50
51
52
53
54
55
56
57
58
59
60


In [89]:
import numpy as np 
a=np.random.randint(10,20,size=(3,3))
print("content of a")
print(a)
print("dimension of a=",a.ndim)
print("shape=",a.shape)
#ittering the the 2d array 
for i in np.nditer(a):
    print(i)
print("-"*50)

content of a
[[12 17 14]
 [12 12 13]
 [13 14 12]]
dimension of a= 2
shape= (3, 3)
12
17
14
12
12
13
13
14
12
--------------------------------------------------


In [99]:
#now itterating the data of 3d array
a=np.random.randint(10,25,size=(2,3,3))
print(a)
print("dimension of a =",a.ndim)
print("shape of a=", a.shape)
for i in np.nditer(a):
    print(i)

[[[19 19 16]
  [24 23 10]
  [14 22 22]]

 [[20 22 21]
  [24 22 19]
  [12 20 17]]]
dimension of a = 3
shape of a= (2, 3, 3)
19
19
16
24
23
10
14
22
22
20
22
21
24
22
19
12
20
17


In [103]:
a=np.arange(2*2*2*2).reshape(2,2,2,2)
print("content of a")
print(a)
print("Dim of a=",a.ndim)
print("---------------------------------")
#itter the data od 4d array
for i in np.nditer(a):
    print(i)

content of a
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Dim of a= 4
---------------------------------
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [109]:
#iterartin the data from object using ndenumerate() with indices and values
import numpy as np
a=np.array([10,20,50,60,70,80,90])
print("content of a ")
print(a)
print("dimension of a=",a.ndim)
for val in np.ndenumerate(a):
    print(val,type(val))

content of a 
[10 20 50 60 70 80 90]
dimension of a= 1
((0,), 10) <class 'tuple'>
((1,), 20) <class 'tuple'>
((2,), 50) <class 'tuple'>
((3,), 60) <class 'tuple'>
((4,), 70) <class 'tuple'>
((5,), 80) <class 'tuple'>
((6,), 90) <class 'tuple'>


In [113]:
#iterartin the data from object using ndenumerate() with indices and values
import numpy as np
a=np.array([10,20,50,60,70,80,90,20]).reshape(4,2)
print("content of a ")
print(a)
print("dimension of a=",a.ndim)
for val in np.ndenumerate(a):
    print(val,type(val))

content of a 
[[10 20]
 [50 60]
 [70 80]
 [90 20]]
dimension of a= 2
((0, 0), 10) <class 'tuple'>
((0, 1), 20) <class 'tuple'>
((1, 0), 50) <class 'tuple'>
((1, 1), 60) <class 'tuple'>
((2, 0), 70) <class 'tuple'>
((2, 1), 80) <class 'tuple'>
((3, 0), 90) <class 'tuple'>
((3, 1), 20) <class 'tuple'>


In [137]:
#iterartin the data from object using ndenumerate() with indices and values
import numpy as np
a=np.random.randint(10,25,size=(2,3,3))
print("content of a ")
print(a)
print("dimension of a=",a.ndim)
for val in np.ndenumerate(a):
    print(val,type(val))

content of a 
[[[12 21 17]
  [12 12 14]
  [24 10 12]]

 [[13 22 23]
  [24 13 19]
  [18 17 19]]]
dimension of a= 3
((0, 0, 0), 12) <class 'tuple'>
((0, 0, 1), 21) <class 'tuple'>
((0, 0, 2), 17) <class 'tuple'>
((0, 1, 0), 12) <class 'tuple'>
((0, 1, 1), 12) <class 'tuple'>
((0, 1, 2), 14) <class 'tuple'>
((0, 2, 0), 24) <class 'tuple'>
((0, 2, 1), 10) <class 'tuple'>
((0, 2, 2), 12) <class 'tuple'>
((1, 0, 0), 13) <class 'tuple'>
((1, 0, 1), 22) <class 'tuple'>
((1, 0, 2), 23) <class 'tuple'>
((1, 1, 0), 24) <class 'tuple'>
((1, 1, 1), 13) <class 'tuple'>
((1, 1, 2), 19) <class 'tuple'>
((1, 2, 0), 18) <class 'tuple'>
((1, 2, 1), 17) <class 'tuple'>
((1, 2, 2), 19) <class 'tuple'>


In [149]:
#iterartin the data from object using ndenumerate() with indices and values
import numpy as np
a=np.random.randint(10,25,size=(2,3,3))
print("content of a ")
print(a)
print("dimension of a=",a.ndim)
for index,val in np.ndenumerate(a):
    print(index,val,type(val))

content of a 
[[[22 18 12]
  [14 12 22]
  [22 16 20]]

 [[17 23 21]
  [23 20 19]
  [11 12 10]]]
dimension of a= 3
(0, 0, 0) 22 <class 'numpy.int32'>
(0, 0, 1) 18 <class 'numpy.int32'>
(0, 0, 2) 12 <class 'numpy.int32'>
(0, 1, 0) 14 <class 'numpy.int32'>
(0, 1, 1) 12 <class 'numpy.int32'>
(0, 1, 2) 22 <class 'numpy.int32'>
(0, 2, 0) 22 <class 'numpy.int32'>
(0, 2, 1) 16 <class 'numpy.int32'>
(0, 2, 2) 20 <class 'numpy.int32'>
(1, 0, 0) 17 <class 'numpy.int32'>
(1, 0, 1) 23 <class 'numpy.int32'>
(1, 0, 2) 21 <class 'numpy.int32'>
(1, 1, 0) 23 <class 'numpy.int32'>
(1, 1, 1) 20 <class 'numpy.int32'>
(1, 1, 2) 19 <class 'numpy.int32'>
(1, 2, 0) 11 <class 'numpy.int32'>
(1, 2, 1) 12 <class 'numpy.int32'>
(1, 2, 2) 10 <class 'numpy.int32'>


In [5]:
#iterartin the data from object using ndenumerate() with indices and values
import numpy as np
a=np.random.randint(10,25,size=(2,3,3))
print("content of a ")
print(a)
print("dimension of a=",a.ndim)
for index,val in np.ndenumerate(a):
    print(index[0],val,type(val))

content of a 
[[[14 20 18]
  [11 18 20]
  [16 21 24]]

 [[16 16 11]
  [20 14 10]
  [11 16 11]]]
dimension of a= 3
0 14 <class 'numpy.int32'>
0 20 <class 'numpy.int32'>
0 18 <class 'numpy.int32'>
0 11 <class 'numpy.int32'>
0 18 <class 'numpy.int32'>
0 20 <class 'numpy.int32'>
0 16 <class 'numpy.int32'>
0 21 <class 'numpy.int32'>
0 24 <class 'numpy.int32'>
1 16 <class 'numpy.int32'>
1 16 <class 'numpy.int32'>
1 11 <class 'numpy.int32'>
1 20 <class 'numpy.int32'>
1 14 <class 'numpy.int32'>
1 10 <class 'numpy.int32'>
1 11 <class 'numpy.int32'>
1 16 <class 'numpy.int32'>
1 11 <class 'numpy.int32'>


In [7]:
print("MatrixNo\tRowNum\tColNum\tValue")
for indval in np.ndenumerate(a):
    print("\t{}\t{}\t{}\t{}".format(indval[0][0],indval[0][1],indval[0][2],indval[1]))

MatrixNo	RowNum	ColNum	Value
	0	0	0	14
	0	0	1	20
	0	0	2	18
	0	1	0	11
	0	1	1	18
	0	1	2	20
	0	2	0	16
	0	2	1	21
	0	2	2	24
	1	0	0	16
	1	0	1	16
	1	0	2	11
	1	1	0	20
	1	1	1	14
	1	1	2	10
	1	2	0	11
	1	2	1	16
	1	2	2	11


In [9]:
print("matrix\trow\tcol\tvalue")
for ind in np.ndenumerate(a):
    print("{}\t{}\t{}\t{}".format(ind[0][0],ind[0][1],ind[0][2],ind[1]))

matrix	row	col	value
0	0	0	14
0	0	1	20
0	0	2	18
0	1	0	11
0	1	1	18
0	1	2	20
0	2	0	16
0	2	1	21
0	2	2	24
1	0	0	16
1	0	1	16
1	0	2	11
1	1	0	20
1	1	1	14
1	1	2	10
1	2	0	11
1	2	1	16
1	2	2	11
